server:
  port: 0

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS atm
    username: sa
    driver-class: org.h2.Driver
    platform: h2
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      dll-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

logging:
  file: logs/atm-customer-service
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true